import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import { Inter } from 'next/font/google';
import { Toaster } from "sonner";
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Expense Tracker App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
            <Toaster />
          <SignedIn>
            {children}  {/* Render children only if signed in */}
          </SignedIn>
          <SignedOut>
            <RedirectToSignIn />  {/* Redirect to sign-in page if not signed in */}
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}